[package]
name = "make"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
eyre = "0.6.12"
serde = { version = "1.0.227", features = ["derive"] }
serde_json = "1.0.145"
